---
# copy the url bash script
- name: copy the bash script to the server
  copy:
    src: latest.sh
    dest: "{{ minecraft.install_path }}"
    owner: "{{ minecraft.user }}"
    group: "{{ minecraft.group }}"
    mode: '0755'

# execute the url bash script
- name: execute the script
  shell: "{{ minecraft.install_path }}/latest.sh"
  register: script_latest_version
  become: true
  become_user: "{{ minecraft.user }}"
  become_method: su

- name: debug task
  debug:
    msg: "{{ script_latest_version }}"

# Server.jar downloaden
- name: download server.jar file
  get_url:
    url: "{{ script_latest_version.stdout }}"
    dest: "{{ minecraft.install_path }}"
    owner: "{{ minecraft.user }}"
    group: "{{ minecraft.group }}"
    mode: '0755'

